#!/usr/bin/env python3

import operator
import os
import sys

subdomains = list(sys.stdin)

results_dict = {}

k = 1

results_file = open('results_gau_order', 'w')

for subdomain in subdomains:
	subdomain = subdomain.rstrip()

	print('[*] Rodando gau no subdomain ' + str(k) + " de " + str(len(subdomains)))

	os.system('echo ' + subdomain + " | gau | sort -u | wc -l > temp")

	temp = open('temp', 'r').readlines()

	results_dict[subdomain] = int(temp[0].rstrip())

	k = k + 1

sorted_results_dict = sorted(results_dict.items(), key=operator.itemgetter(1), reverse=True)

for item in sorted_results_dict:
	print(item[0])
	results_file.write(item[0] + '\n')

os.system('rm temp')